### ISSUE TITLE
OWL vs OWL 2

### ISSUE THREAD

**Issue by skodapetr** [SEMICeu/style-guide#19]
To quote a single site (https://semiceu.github.io/style-guide/public-review/arhitectural-clarifications.html):
```This is addressed with lightweight ontologies expressed in OWL 2.```
```formal ontology expressed in OWL```

I assume it is still the same version and not OWL 1. Or is this an intention 
and both OWL 1 and OWL 2 shall be used for different purpose?

**Comment by costezki** [comment]
We decided to refer, in this style guide, to the latest version of OWL only, i.e. OWL 2.
