### ISSUE TITLE
Do Guidelines and conventions contains all rules?

### ISSUE THREAD

**Issue by skodapetr** [SEMICeu/style-guide#22]
It seems like section "Guidelines and conventions" contains all rules from (General conventions, Conceptual model conventions (UML), ... ). There are even links to those section e.g. https://semiceu.github.io/style-guide/public-review/guidelines-and-conventions.html#_general_conventions but link from the menu is to: https://semiceu.github.io/style-guide/public-review/gc-general-conventions.html

As a result it is not clear whether the "Guidelines and conventions" contains all rules or not.

**Comment by csnyulas** [comment]
The ["Guidelines and conventions"](https://semiceu.github.io/style-guide/public-review/guidelines-and-conventions.html) page contains links to all the six (sub-)sections, each containing different categories of rules/conventions. Recently we reordered the list to provide a more logical organisation/presentation. These six sections contain ALL the rules provided in this Style Guide. All links to the sub-sections work.  AFAICT now everything is OK, so, I will close the ticket.
@skodapetr, in case there are still some issues left, which I didn't observe, or didn't understood, please feel free to reopen the ticket.

**Note:** BTW, the purpose of the "Guidelines and conventions" page was not to contain links to all the rules, but rather to serve as an intro page to the conventions sections, and provides pointers to the sub-sections. To provide an overview of all the rules, in one place, you can use the ["Index of Rules"](https://semiceu.github.io/style-guide/public-review/index-of-rules.html) page, or the ["Style Guide as a Whole"](https://semiceu.github.io/style-guide/public-review/style-guide-whole.html) page.
