### ISSUE TITLE
rdfs:subPropertyOf missing in SC-R2

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/style-guide#23]
In [SC-R2](https://semiceu.github.io/style-guide/public-review/gc-semantic-conventions.html#sec:sc-r2) `rdfs:subPropertyOf` is missing. However, its usage is suggested multiple times in [Clarifications on "reuse"](https://semiceu.github.io/style-guide/public-review/clarification-on-reuse.html), which I agree with.

**Comment by costezki** [comment]
Thank you, Jakub. 
Mention of `rdfs:subPropertyOf` has been added in SC-R2.
