### ISSUE TITLE
Specification of the documentation of an application profile

### ISSUE THREAD

**Issue by tfrancart** [SEMICeu/style-guide#55]
SHACL Play can generate a documentation from a SHACL definition of an application profile (https://shacl-play.sparna.fr/play/doc)
This documentation contains property tables with following columns:
  - property label
  - property URI
  - expected value (can contain either a list of allowed values, a reference to a class, to a node shape, or simply IRI / Literal)
  - cardinalities
  - description

Does the style guide have any recommendation on how to best provide a human-readable documentation of shapes ? especially regarding how the properties table should be generated ?

**Comment by costezki** [comment]
Thank you, Thomas, for the feedback on this. 

The rule itself is a general statement that the “data specification” overall shall be human-readable (pointed out in #57). However, the contents of it may cover the ontology, the shapes and some other artefacts. 

Now, each artefact may still need to have its specificities. For example, the shapes, as you well point out, shall follow some description good practice (e.g. metadata supported by shacl-play.sparna, or DCAP Dublin Core Application Profile) and the ontology as well (e.g. LODE, Widoco). 

We will make this mention in the rule description.
