### ISSUE TITLE
A technical comment/question to Human-readable form (PC-R6)

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/style-guide#57]
[Human-readable form](https://semiceu.github.io/style-guide/public-review/gc-publication-conventions.html#sec:pc-r6) (PC-R6) says "Each artefact shall have a corresponding human-readable form representing the model documentation".  An artefact according to [Data specification and artefact types](https://semiceu.github.io/style-guide/public-review/arhitectural-clarifications.html#sec:data-specification-and-artefact-types) may be among other things a formal ontology expressed in OWL 2 or data shapes expressed in SHACL, which according to PC-R6 therefore also **shall** have human-readable form? 

Or does PC-R6 actually want to say "Each **data specification** shall have a corresponding human-readable form representing the model documentation"? 

Conf. though Issue #55 about human-readable documentation of shapes.

**Comment by csnyulas** [comment]
Indeed, the use of word "asset" was confusing (as you correctly made the link also to #55).
We meant to say "data specification", and we have corrected it in the source. See above commit.
