### ISSUE TITLE
Concept versus Class

### ISSUE THREAD

**Issue by GeertThijs** [SEMICeu/style-guide#58]
In § What is a conceptual model? You are quick to substitute the notion of Concept with the notion of Class. It would maybe be good to explain that Classes are a sort of extension of Concepts, by adding things like attributes to further describe the characteristics of instances of some Concept.

**Comment by csnyulas** [comment]
I read carefully the above mentioned section, and I don't think we are conflating the notion of Concept with that of the Class.

 When we talk about concepts (and we mostly talk about concepts in this section - the word Class is mentioned only in the context of UML elements that are recommended to be used, along with other UML elements such as connectors, etc), we mean not only classes by them, but any the "concept" that help with the conceptualization and representation of a given domain.
So, a "concept" in the conceptual model can be seen more like an OWL entity (which can be not only class, but also individual, property, dataype, etc), rathr than an OWL class. The statements in this section all make sense with this interpretation. 

So, a "concept" is not the same as a "class", and talking about them like that would be inaccurate. Saying something like 
"_Classes are **specific type** of Concepts, **extending them** by adding things like attributes to further describe the characteristics of instances of some Concept._" would make sense, in principle. However, if we say this, then we need to describe the other type of concepts as well (that are not to be interpreted as classes), and that would add just too much unnecessary detail, irrelevant at this part of the guide, which would likely be incomplete, and someone else would complain about that later.

I would close this issue unless there is disagreement or further comments from @GeertThijs @costezki or other contributors.
