### ISSUE TITLE
Domain & Range

### ISSUE THREAD

**Issue by GeertThijs** [SEMICeu/style-guide#60]
In § Fixed UML interpretation. Maybe explain why domain & range declarations are left out of the OWL ontology (and kept for the SHACL shapes). I agree with the idea but think it would be good to explain why (eg greater flexibility in choice of range when using the vocabulary for different application profiles).

**Comment by costezki** [comment]
No expressions of (a) property domain specification (rdfs:domain) and (b) property range specification (rdfs:range) shall be used unless justified as absolutely necessary. The need for setting property domain and range constraints shall be is better fulfilled by the data shapes expressed in SHACL language.

See: https://semiceu.github.io/style-guide/public-review/gc-semantic-conventions.html#sec:sc-r2
