### ISSUE TITLE
Names of enumerations

### ISSUE THREAD

**Issue by GeertThijs** [SEMICeu/style-guide#61]
In § Case sensitivity and charsety. Why should the name of an enumeration start with a lowercase letter? In the UML metamodel an enumeration is a specialisation of the classifier Datatype. Datatype names start with a capital, so why not enumerations?

**Comment by csnyulas** [comment]
The logic of this recommendation is to have consistency between the naming style of the enumerations declared in a CV or AP, and other externally maintained, and often reused, vocabularies and authority tables (e.g. [at-voc:access-right](http://publications.europa.eu/resource/authority/access-right), [at-voc:language](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/language)).
Does this make sense @GeertThijs ?

We are aware that many CVs and APs currently don't follow this recommendation. This is a style **guide**, with recommendations. It is up to each group and project to decide if they want to follow or not any given the recommendation in the guide.

**Comment by costezki** [comment]
We have updated the recommendation, relaxing it on the packages, data types and enumerations.
