### ISSUE TITLE
Multiple classification

### ISSUE THREAD

**Issue by GeertThijs** [SEMICeu/style-guide#68]
It turns out that generalizations sets are rather important in conceptual modeling. It should be clear that there can exist several kinds of subclassifications that do not exclude each other; Eg an Organization can be a publicOrganization and at the same time a RegisteredOrganization (or not). Allows double typing of data.

**Comment by costezki** [comment]
That is correct. We do not restrict in any sense multiple inheritance, as we do not intend to provide comments on the modelling practices. This is entirely up to the knowledge engineer.
