### ISSUE TITLE
Provide a consistent ordering of guideline groups (especially concerning the "Methodology Conventions" group)

### ISSUE THREAD

**Issue by csnyulas** [SEMICeu/style-guide#69]
The "Methodology Conventions" group is listed in a different order (as second) on the ["Guidelines and Conventions" page](https://semiceu.github.io/style-guide/public-review/guidelines-and-conventions.html) than in other places (navigation bars, index page, etc., where it is listed in the next to last position).

We should do our best to be consistent with the ordering of the rule groups across the entire Style Guide. The question is: What is the best place for the "Methodology conventions" section to be listed at?
Is it the _next to last_ position (just before the Publication Conventions), the _second_ position (after the "General conventions", but before "Conceptual model conventions"), or perhaps should it be the very _first_ group?

I think that the first position is perhaps the most appropriate one for the "Methodology Conventions" group, especially if we look at the rules [MC-R1](https://semiceu.github.io/style-guide/public-review/gc-methodology-conventions.html#sec:mc-r1) ("Follow a methodology") and [MC-R2](https://semiceu.github.io/style-guide/public-review/gc-methodology-conventions.html#sec:mc-r2) ("Scope and goals definition"), which should happen at the very beginning of the data specification development process, but [MC-R3](https://semiceu.github.io/style-guide/public-review/gc-methodology-conventions.html#sec:mc-r3) ("Modularisation") might not be relevant in many use cases, so it might seem inappropriate to some to have this rule listed before the rules in the "General conventions" section.

@costezki, @bertvannuffelen, @EmidioStani, @NatasaSofou, @pfragkou or anyone else interested in this topic, please let me know what you think, in the comments below, and I am happy to implement whatever solution ends up as the clear winner.

**Comment by EmidioStani** [comment]
I believe that the "Methodology Conventions" should come as first before "General conventions", as the former is the generic approach, the latter is more on the "operational" part

**Comment by jitsedc** [comment]
I agree with you and Emidio here. With regards to MC-R3, I think it makes sense under Methodology because to me it is clear this comes before GC-R1. You want to determine scope and the size of the domain before even looking into actual modelling. However, this is a process that never stops (which is also the case for MC-R2). These two fit together well under MC.
