### ISSUE TITLE
Issues with HTML rendering of the style guide

### ISSUE THREAD

**Issue by andrea-perego** [SEMICeu/style-guide#7]
There are some rendering issues in the HTML version of the style guide on GitHub pages:

https://semiceu.github.io/style-guide/

I list below those I have identified so far.

1. Images are not displayed, and the corresponding markup is shown as plain text - e.g., [§2.2](https://semiceu.github.io/style-guide/#sec:layers-components):

    > image::../img/uml.png[The main components of the eProcurement ontology and their relation to each other and the UML conceptual model,scaledwidth=99.0%]

2. References to bibliographic entries and cross-references for sections and figures are not interpreted - see, e.g., [§2.2](https://semiceu.github.io/style-guide/#sec:layers-components):

    > The relations between them are represented in Figure #fig:components[1] where each component is represented as an UML package.
    > ...
    > These formal modules are derived from the conceptual model through model transformations as described in Section #sec:process-approach following the rules laid out in .

3. Mathcal commands are not interpreted, and shown as plain text - see, e.g., [§6.2](https://semiceu.github.io/style-guide/#sec:semantics):

    > Description logics provide a concise language for OWL axioms and expressions. DLs are characterised by their expressive features. The description logic that supports all class expressions with \(>, \bot, \sqcap, \sqcup, \neg, \exists\) and \(\forall\) is known as \(\mathcal{ALC}\) (which originally used to be an abbreviation for Attribute Language with Complement). For a formal introduction into DL please consult .

4. The "References" section lists just citation keys, but not the full bibliographic entries.

**Comment by costezki** [comment]
The style-guide has been going through major refactoring since December, Andrea. I believe the issues mentioned above have been fixed in the process.
