### ISSUE TITLE
Lightweight ontologies (chapter 2.2)

### ISSUE THREAD

**Issue by RiittaA** [SEMICeu/style-guide#71]
In Style Guide (chapter 2.2, Ontology) is stated:
- In the SEMIC context, we only consider lightweight ontologies [[defined in rule SC-R2](https://semiceu.github.io/style-guide/public-review/gc-semantic-conventions.html#sec:sc-r2)]

We are afraid that this is too lightweight and limits expressivity too much. The limitation is perhaps due to restriction of UML notation, but makes later usage of data models more challenging.

- In our approach, we are going to use OWL profiles that already narrow expressivity, meaning OWL 2 profiles (EL/QL/RL) that are already quite narrow.
- Limiting the expressivity of OWL further loses expressive power which is useful in mapping ontologies together, enriching data with inferencing and performing semantic mapping between datasets.
- With relying on the "lightweight" approach, we can easily end up in a situation where users merely tag data with commonly interpreted resources. This will make data machine-readable but not machine-interpretable to any meaningful extent, similar to how e.g. DC Terms functions to a large extent.
- The primary use for semantic interoperability is the fact that we are harnessing computation to make explicit the implicit links and features within data structures, and to allow for clear separation of what has been asserted and what can be derived from the data. Thus rich inferencing allows us to avoid situations where derived records would have to be stored and managed as separate assertions and not as dynamic inferred views into the primary records.

**Comment by costezki** [comment]
In this style guide, we do not prevent people from using heavyweight ontologies. What we say is that the Core Vocabularies shall contain a lightweight ontology artefact. If your use case demands more logical axioms, then they can be placed in a separate OWL artefact that  (imports and) extends the core definitions of classes and properties. This is done, for example, in eProcurement Ontology.

**Comment by csnyulas** [comment]
Closing this as a Note with detailed explanation has been added at the end of the  [SC-R2](https://semiceu.github.io/style-guide/public-review/gc-semantic-conventions.html#sec:sc-r2) convention (see above commit).
